Repository cydran/cydran, pull requests merged in 2020-08, with the labels that each got.

#482 Dependency and docs updates
  md_docs/general_overview.md
  package-lock.json
  package.json
Labels: PR submitted, document

#484 Added support for c:value on templates in c:each
  src/Component.ts
Labels: enhancement

#485 Simplify logging calls with errors
  package-lock.json
  package.json
  src/Component.ts
  src/Errors.ts
  src/Logger.ts
  src/Registry.ts
  src/Utils.ts
  src/properties.json
  test/Component.ScopeImpl.spec.ts
  test/Errors.spec.ts
Labels: maintenance

#490 #488 add hasRegistration() boolean method
  package-lock.json
  package.json
  src/Component.ts
  src/Interfaces.ts
  src/Registry.ts
  test/Registry.spec.ts
Labels: PR submitted, enhancement, testing
